name: Tests

on: ["push", "pull_request"]

jobs:
  feature:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: xdebug

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate Key
        run: php artisan key:generate

      - name: Run Migrations
        run: php artisan migrate

      - name: Tests
        run: ./vendor/bin/pest --compact --group=feature
