name: Tests

on: ["push", "pull_request"]

jobs:
  feature:
    runs-on: ubuntu-latest
    container:
      image: noxyz20/laravel-image:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate Key
        run: php artisan key:generate

      - name: Setup Database
        run: |
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=./database/testing.sqlite" >> .env
          touch ./database/testing.sqlite

      - name:  Migrate
        run: php artisan migrate
        
      - name: install dependencies
        run: pnpm install

      - name: Build javascript
        run: pnpm build
      
      - name: Permissions
        run: chmod -R 777 *

      - name: Tests
        run: ./vendor/bin/pest --compact --group=feature --log-junit="pest-xml/report.xml"

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-results
          path: .pest-xml/
          if-no-files-found: ignore